let suggestions = [
    "Computer Graphics",
    "Computer Networks",
    "Data Structures and algorithms",
    "Software Engineering",
    "Python",
    "C++",
    "C",
    "java programming",
    "Javascript",
    "Maths",
    "Database Management system",
    "DBMS",
    "OOPS",
    "Information Technology",
    "Web Development",
];