let suggestions = [
    "kwikNotes",
    "Operating System",
    "Data Structures and algorithms",
    "Software Engineering",
    "Python",
    "C++/C",
    "java programming",
    "Javascript",
    "Maths",
    "English",
    "Contact",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "How to learn JavaScript",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];